---
- name: Upgrade pip setuptools
  pip:
    name: setuptools
    state: latest
  become: yes

- name: Add requirements.txt
  copy:
    src: requirements.txt
    dest: /tmp/requirements.txt

- name: Pip install requirements
  pip:
    requirements: /tmp/requirements.txt
  become: yes
